name: Build and Push Docker Containers to GitHub Container Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push keyfade-backend container
      - name: Build and Push keyfade-backend container
        run: |
          cd keyfade-backend
          docker build -t ghcr.io/${{ github.repository_owner }}/keyfade-backend:latest .
          docker push ghcr.io/${{ github.repository_owner }}/keyfade-backend:latest

      # Build and push keyfade-frontend container
      - name: Build and Push keyfade-frontend container
        run: |
          cd keyfade-frontend
          docker build -t ghcr.io/${{ github.repository_owner }}/keyfade-frontend:latest .
          docker push ghcr.io/${{ github.repository_owner }}/keyfade-frontend:latest
